name: Procesar Reporte Banrep

on:
  workflow_dispatch:
    # AQUÍ ES DONDE DEFINES QUE EL ENDPOINT PUEDE RECIBIR EL FILE_ID
    inputs:
      file_id:
        description: 'ID del archivo enviado desde n8n'
        required: true

jobs:
  ejecutar-proceso:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Descargar el código
        uses: actions/checkout@v3

      - name: 2. Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: 3. Instalar dependencias
        run: pip install google-api-python-client google-auth

      - name: 4. Ejecutar el script
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
          ID_ARCHIVO_DRIVE: ${{ github.event.inputs.file_id }}
        run: python main.py
